//------------------------------------------------------------------------------
// <auto-generated>
// This enum was auto generated by HhhPrefabManager.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HhhPrefabManagement
{
    /// <summary>
    /// Auto-generated enum representing all prefabs spawned by the HhhPrefabManager
    /// </summary>
    public enum PrefabType : byte
    {
		GenericCube = 0,
		Cube1 = 1,
		swotd = 2,

    }
}